config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'parking_lots/update'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about'  => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get '/book_now/:id' => 'parking_lots#update' ,:as => :book_now
  get '/book_slot/:id' => 'parking_lots#update_app'
  resources :parkings
  resources :transactions
  post 'payment' => 'transactions#payment'
  get 'end_transaction/:id' =>'transactions#update', :as=> :end_transaction
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  root 'static_pages#home'

namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    get 'book_now/:user_id/:id' => 'parking_lots#update', :as =>:book_now_api
    get 'booked_online/:id' => 'transactions#booked_online'
    get 'parking_status/:id' => 'parking_lots#parking_status'
    get 'entry/' => 'parking_lots#entry'
    get 'exit/:id' => 'transactions#exit'
    get 'all_transactions/:id' => 'transactions#all_transactions'
    resources :parkings
    resources :sessions
    end

end

end

app/models/parking.rb
class Parking < ActiveRecord::Base
  has_many :transactions
  has_many :parking_lots
end

app/controllers/api/v1/parkings_controller.rb
module Api::V1
class ParkingsController < ApplicationController

  def index
    @parkings=Parking.all
    respond_to do |format|
      format.json { render json: @parkings }
    end
  end

  def show
    @parking=Parking.find(params[:id])
    @parkinglots=@parking.parking_lots
    respond_to do |format|
      format.json { render json: @parkinglots }
    end
  end
end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  
  def index
    @parkings=Parking.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @parkings }
    end
  end

  def edit
  end

  def update
  end

  def show
    @parking=Parking.find(params[:id])
    @parkinglots=@parking.parking_lots
    @user = current_user
  end
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/parkings/edit.html.erb
<h1>Parkings#edit</h1>
<p>Find me in app/views/parkings/edit.html.erb</p>

app/views/parkings/index.html.erb
<%if logged_in?%>
          <div id="right-panel"></div>
          <div id="map"></div>
    <script>

var map;
function initMap() {
  var bounds = new google.maps.LatLngBounds();
  var NagpurCenter = {lat: 28.6100, lng: 77.2300};
//  var coordinates= [{lat:28.6629,lng:77.2100},{lat:28.5472, lng:77.2508},{lat:28.6328, lng:77.2197},{lat:28.5789, lng:77.2439},{lat:28.5769, lng:77.1961},{lat:28.5290, lng:77.2191}];
//  var info=["Karol Bagh","Nehru Place", "Connaught Place", "Lajpat Nagar", "Sarojni Nagar", "Select City Walk"];
    //1. Karol Bagh 1.Nehru place 2.Connaught Place 3.Lajpat Nagar 4.Sarojni Nagar 5.Select City Walk
  map = new google.maps.Map(document.getElementById('map'), {
    center: NagpurCenter,
    zoom: 12
  });
  var marker = new google.maps.Marker({
      position: NagpurCenter,
      map: map,
      title: 'Hello World!'
    });
      setMarkers(map);
       bounds.extend(marker.position);
       map.fitBounds(bounds);
       var listener = google.maps.event.addListener(map, "idle", function () {
         map.setZoom(12);
    google.maps.event.removeListener(listener);
    });

      //var contentString = //Hit a url here to get data!;
    // Create the DIV to hold the control and call the CenterControl() constructor
  // passing in this DIV.
  var centerControlDiv = document.createElement('div');
  var centerControl = new CenterControl(centerControlDiv, map,NagpurCenter);

  centerControlDiv.index = 1;
  map.controls[google.maps.ControlPosition.BOTTOM_LEFT].push(centerControlDiv);
}

/**
 * The CenterControl adds a control to the map that recenters the map on Chicago.
 * This constructor takes the control DIV as an argument.
 * @constructor
 */
 function findPath(start,end,map){
  var directionsDisplay = new google.maps.DirectionsRenderer;
  var directionsService = new google.maps.DirectionsService;
  directionsDisplay.setMap(map);
  directionsDisplay.setPanel(document.getElementById('right-panel'));
    calculateAndDisplayRoute(directionsService, directionsDisplay,start,end);
 }

 function calculateAndDisplayRoute(directionsService, directionsDisplay,startLoc,endLoc) {
  var start = startLoc;
  var end = endLoc;
  directionsService.route({
    origin: start,
    destination: end,
    travelMode: google.maps.TravelMode.DRIVING
  }, function(response, status) {
    if (status === google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
    } else {
      window.alert('Directions request failed due to ' + status);
    }
  });
}


function CenterControl(controlDiv, map,NagpurCenter) {

  // Set CSS for the control border.
  var controlUI = document.createElement('div');
  controlUI.style.backgroundColor = '#607D8B';
  controlUI.style.border = '2px solid  #D9D9D7';
  controlUI.style.borderRadius = '3px';
  controlUI.style.boxShadow = '0 2px 6px rgba(0,0,0,.3)';
  controlUI.style.cursor = 'pointer';
  controlUI.style.marginBottom = '22px';
  controlUI.style.textAlign = 'center';
  controlUI.title = 'Click to recenter the map';
  controlDiv.appendChild(controlUI);

  // Set CSS for the control interior.
  var controlText = document.createElement('div');
  controlText.style.color = '#D9D9D7';
  controlText.style.fontFamily = 'Roboto,Arial,sans-serif';
  controlText.style.fontSize = '16px';
  controlText.style.lineHeight = '38px';
  controlText.style.paddingLeft = '5px';
  controlText.style.paddingRight = '5px';
  controlText.innerHTML = 'Click to find nearest parking to your location!';
  controlUI.appendChild(controlText);

  // Setup the click event listeners: simply set the map to Chicago.
  controlUI.addEventListener('click', function() {
    var location=getGeolocation(NagpurCenter);
  });

}

function setMarkers(map){

      var marker, i
<% @parkings.each do |parking| %>
 var coordinates = {lat:<%=parking.lat%> , lng: <%=parking.lng%>};
 var info ='<%=parking.name%>';
 contentString=
'<center><h3 id="firstHeading" class="firstHeading"><%=parking.name%></h3></center>'+
'<div id="bodyContent">'+
'<p> Total Capacity: <%=parking.total_capacity%></p>'+
'<p> Filled: <%=parking.filled%></p>'+
'<p> Current Rate(per hour): 100</p>'+
'</div>'+
'<%= button_to "Show Complete Status", parking_path(parking), :class => "btn btn-primary center-block", :method => :get  %>';



  var marker = new google.maps.Marker({
          map: map, title: info , position: coordinates
        });
        map.setCenter(marker.getPosition())


        var infowindow = new google.maps.InfoWindow()

        google.maps.event.addListener(marker,'click', (function(marker,contentString,infowindow){
        return function() {
           infowindow.setContent(contentString);
           infowindow.open(map,marker);
        };
    })(marker,contentString,infowindow));



/*
        var infowindow = new google.maps.InfoWindow({
          content: contentString
        });
        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });
*/
  <% end %>
}

function getGeolocation(NagpurCenter){
var initialLocation;
var browserSupportFlag =  new Boolean();
var end = {lat: 28.6100, lng: 77.2300};

  // Try W3C Geolocation (Preferred)
  if(navigator.geolocation) {
    browserSupportFlag = true;
    navigator.geolocation.getCurrentPosition(function(position) {
      initialLocation = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
      map.setCenter(initialLocation);
      findPath(initialLocation,end,map);
      start=initialLocation;
    }, function() {
      handleNoGeolocation(browserSupportFlag);
    });
  }
  // Browser doesn't support Geolocation
  else {
    browserSupportFlag = false;
    handleNoGeolocation(browserSupportFlag);
  }

  function handleNoGeolocation(errorFlag) {
    if (errorFlag == true) {
      alert("Geolocation service failed.");
      initialLocation = NagpurCenter;
    } else {
      alert("Your browser doesn't support geolocation. We've placed you in Siberia.");
      initialLocation = NagpurCenter;
    }
    map.setCenter(initialLocation);
  }
  return initialLocation;
}

function calulateDistance(data,initialLocation){

  var service = new google.maps.DistanceMatrixService();
  service.getDistanceMatrix(
    {
      origins: data,
      destinations: [destination],
      travelMode: google.maps.TravelMode.DRIVING,
      transitOptions: TransitOptions,
      unitSystem: UnitSystem,
      durationInTraffic: false,
      avoidHighways: true,
      avoidTolls: true,
    }, callback);

  function callback(response, status) {
    if (status == google.maps.DistanceMatrixStatus.OK) {
    var origins = response.originAddresses;
    var destinations = response.destinationAddresses;

    for (var i = 0; i < origins.length; i++) {
      var results = response.rows[i].elements;
      for (var j = 0; j < results.length; j++) {
        var element = results[j];
        var distance = element.distance.text;
        var duration = element.duration.text;
        var from = origins[i];
        var to = destinations[j];
      }
    }
  }

  }

}

    </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA6UmP5y2ulrLl7wgkjMi9A-WyeYyPbJBs&callback=initMap"
        async defer></script>





<%else%>

<% redirect_to root_url %>

<%end%>

app/views/parkings/show.html.erb
  <center>
<button type="button" class="btn btn-warning btn-md" data-toggle="modal" data-target="#myModal">
  Update Vehicle Number
</button>

<%= link_to "Payment", new_transaction_path, class: "btn btn-danger btn-md" %>
  <%i=1%>
  <% @parkinglots.each do |lot| %>

       <%if (lot.availaible)%>
        <%= link_to "#{lot.slot_id}", book_now_path(lot.id) , :class => "btn btn-primary",:data => {:confirm => 'Are you sure?You will be billed from now'} %>
       <%else%>
        <%= link_to "#{lot.slot_id}",book_now_path(lot.id) ,:class => "btn btn-primary disabled", :method => :get  %>
       <%end%>
       <%i=i+1%>
  <%end%>
</center>
  <tbody class="ptbody">
  <table align="center" class="ptable">

  <tr class="ptr">
    <td class="ptd">

    <%if (@parkinglots[0].availaible)%>
      <%= link_to "#{@parkinglots[0].slot_id}", book_now_path(@parkinglots[0].id) , :id => "pbtn",:class => "btn btn-success",:data => {:confirm => 'Are you sure?You will be billed from now'} %>
    <%else%>
      <%= link_to "#{@parkinglots[0].slot_id}",book_now_path(@parkinglots[0].id) ,:id => "pbtn",:class => "btn btn-primary disabled", :method => :get  %>
    <%end%>

   </td>
   <td class="ptd">

   <%if (@parkinglots[1].availaible)%>
     <%= link_to "#{@parkinglots[1].slot_id}", book_now_path(@parkinglots[1].id) , :id => "pbtn",:class => "btn btn-success",:data => {:confirm => 'Are you sure?You will be billed from now'} %>
   <%else%>
     <%= link_to "#{@parkinglots[1].slot_id}",book_now_path(@parkinglots[1].id) ,:id => "pbtn",:class => "btn btn-primary disabled", :method => :get  %>
   <%end%>

  </td>
  <td class="ptd">

  <%if (@parkinglots[2].availaible)%>
    <%= link_to "#{@parkinglots[2].slot_id}", book_now_path(@parkinglots[2].id) , :id => "pbtn",:class => "btn btn-success",:data => {:confirm => 'Are you sure?You will be billed from now'} %>
  <%else%>
    <%= link_to "#{@parkinglots[2].slot_id}",book_now_path(@parkinglots[2].id) ,:id => "pbtn",:class => "btn btn-primary disabled", :method => :get  %>
  <%end%>

 </td>
 <td class="ptd">

 <%if (@parkinglots[3].availaible)%>
   <%= link_to "#{@parkinglots[3].slot_id}", book_now_path(@parkinglots[3].id) , :id => "pbtn",:class => "btn btn-success",:data => {:confirm => 'Are you sure?You will be billed from now'} %>
 <%else%>
   <%= link_to "#{@parkinglots[3].slot_id}",book_now_path(@parkinglots[3].id) ,:id => "pbtn",:class => "btn btn-primary disabled", :method => :get  %>
 <%end%>

</td>
<td class="ptd">

<%if (@parkinglots[4].availaible)%>
  <%= link_to "#{@parkinglots[4].slot_id}", book_now_path(@parkinglots[4].id) , :id => "pbtn",:class => "btn btn-success",:data => {:confirm => 'Are you sure?You will be billed from now'} %>
<%else%>
  <%= link_to "#{@parkinglots[4].slot_id}",book_now_path(@parkinglots[4].id) ,:id => "pbtn",:class => "btn btn-primary disabled", :method => :get  %>
<%end%>

</td>
<td class="ptd">

<%if (@parkinglots[5].availaible)%>
  <%= link_to "#{@parkinglots[5].slot_id}", book_now_path(@parkinglots[5].id) , :id => "pbtn",:class => "btn btn-success",:data => {:confirm => 'Are you sure?You will be billed from now'} %>
<%else%>
  <%= link_to "#{@parkinglots[5].slot_id}",book_now_path(@parkinglots[5].id) ,:id => "pbtn",:class => "btn btn-primary disabled", :method => :get  %>
<%end%>

</td>


<!--    <td class="ptd"><button type="button" id="pbtn" class="btn btn-success"><%=@parkinglots[1].slot_id%></button></td>
    <td class="ptd"><button type="button" id="pbtn" class="btn btn-success"><%=@parkinglots[2].slot_id%></button></td>
    <td class="ptd"><button type="button" id="pbtn" class="btn btn-success"><%=@parkinglots[3].slot_id%></button></td>
    <td class="ptd"><button type="button" id="pbtn" class="btn btn-success"><%=@parkinglots[4].slot_id%></button><-<img src="C:\Users\admin\Desktop\ADI\images\s1.png">-</td>
    <td class="ptd"><button type="button" id="pbtn" class="btn btn-success"><%=@parkinglots[5].slot_id%></button></td>
-->

  </tr>
  <tr class="ptr">
    <td style="background-color:#455A64; border:none;width:1000px;" class="ptd">EXIT | HERE</td>
    <td style="background-color:lightgrey; border:none;" class="ptd"></td>
    <td style="background-color:lightgrey; border:none;" class="ptd"></td>
    <td style="background-color:lightgrey; border:none;" class="ptd"></td>
    <td style="background-color:lightgrey; border:none;" class="ptd"></td>
  <!--  <td><button type="button" class="btn btn-success" id="pbtn"><%=@parkinglots[6].slot_id%></button></td>
  -->
  <td class="ptd">

  <%if (@parkinglots[6].availaible)%>
    <%= link_to "#{@parkinglots[6].slot_id}", book_now_path(@parkinglots[6].id) , :id => "pbtn",:class => "btn btn-success",:data => {:confirm => 'Are you sure?You will be billed from now'} %>
  <%else%>
    <%= link_to "#{@parkinglots[6].slot_id}",book_now_path(@parkinglots[6].id) ,:id => "pbtn",:class => "btn btn-primary disabled", :method => :get  %>
  <%end%>

  </td>

  </tr>
  <!-- <tr>
    <td style="background-color:grey; border:none;">- - -</td>
    <td style="background-color:grey; border:none;">- - -</td>
    <td style="background-color:grey; border:none;">-|-</td>
    <td style="background-color:grey; border:none;">-|-</td>
    <td><button type="button" class="btn btn-success">9</button></td>
    <td style="background-color:grey; border:none;">-|-</td>


  </tr> -->
  <tr class="ptr">
    <td class="ptd"><!--<img src="<%=image_url('reserved.png')%>">--></td>

    <td class="ptd">

    <%if (@parkinglots[7].availaible)%>
      <%= link_to "#{@parkinglots[7].slot_id}", book_now_path(@parkinglots[7].id) , :id => "pbtn",:class => "btn btn-success",:data => {:confirm => 'Are you sure?You will be billed from now'} %>
    <%else%>
      <%= link_to "#{@parkinglots[7].slot_id}",book_now_path(@parkinglots[7].id) ,:id => "pbtn",:class => "btn btn-primary disabled", :method => :get  %>
    <%end%>

    </td>
    <td class="ptd">

    <%if (@parkinglots[8].availaible)%>
      <%= link_to "#{@parkinglots[8].slot_id}", book_now_path(@parkinglots[8].id) , :id => "pbtn",:class => "btn btn-success",:data => {:confirm => 'Are you sure?You will be billed from now'} %>
    <%else%>
      <%= link_to "#{@parkinglots[8].slot_id}",book_now_path(@parkinglots[8].id) ,:id => "pbtn",:class => "btn btn-primary disabled", :method => :get  %>
    <%end%>

    </td>

    <!-- <td class="ptd"><button type="button" id="pbtn" class="btn btn-success"><%=@parkinglots[7].slot_id%></button></td>
    <td class="ptd"><button type="button" id="pbtn" class="btn btn-success"><%=@parkinglots[8].slot_id%></button></td>
  -->
    <td class="ptd"><img src="<%=image_url('s1.png')%>"><!--<button type="button" class="btn btn-success">12</button>--></td>
    <td style="background-color:lightgrey; border:none;" class="ptd"></td>
    <td class="ptd"><button type="button" id="pbtn" class="btn btn-success"><img src="<%=image_url('reserved.png')%>"></button></td>

  </tr>
  <tr class="ptr">
    <td class="ptd"><button type="button" id="pbtn" class="btn btn-success"><img src="<%=image_url('reserved.png')%>"></button></td>
    <td class="ptd"><button type="button" id="pbtn" class="btn btn-success"><%=@parkinglots[9].slot_id%></button></td>
    <td class="ptd"><button type="button" id="pbtn" class="btn btn-success"><%=@parkinglots[10].slot_id%></button></td>
    <td class="ptd"><button type="button" id="pbtn" class="btn btn-success"><%=@parkinglots[11].slot_id%></button></td>
    <td  class="ptd" style="background-color:#455A64; border:none;">ENTER | HERE</td>
    <td class="ptd"></td>
    <!-- <td style="background-color:red;text-align:right; border:none;">|EN</td>
    <td style="background-color:red;text-align:left; border:none;">TER|</td> -->

  </tr>

  </table>
  </tbody>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Vehicle Number Update!</h4>
      </div>
      <div class="modal-body">
        <p>Do you want to update your Vehicle number?</p>
        <%= form_for @user, url: user_path(@user), html: {class: "nifty_form"} do |f| %>
        <%= f.text_field :car_number, placeholder: "    Enter your new vehicle number here!" %>
        <br><br>
        <div class="col-md-12">
          <div class="col-md-6">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
          <div class="col-md-6">
            <%= f.submit "Update",class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
        
      </div>
 <!--      <div class="modal-footer">
   <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
   <button type="button" class="btn btn-primary">Save changes</button>
 </div> -->
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function($) {
    $('#myModal').modal('toggle');
    
  });
</script>

app/views/parkings/update.html.erb
<h1>Parkings#update</h1>
<p>Find me in app/views/parkings/update.html.erb</p>