config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'parking_lots/update'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about'  => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get '/book_now/:id' => 'parking_lots#update' ,:as => :book_now
  get '/book_slot/:id' => 'parking_lots#update_app'
  resources :parkings
  resources :transactions
  post 'payment' => 'transactions#payment'
  get 'end_transaction/:id' =>'transactions#update', :as=> :end_transaction
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  root 'static_pages#home'

namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    get 'book_now/:user_id/:id' => 'parking_lots#update', :as =>:book_now_api
    get 'booked_online/:id' => 'transactions#booked_online'
    get 'parking_status/:id' => 'parking_lots#parking_status'
    get 'entry/' => 'parking_lots#entry'
    get 'exit/:id' => 'transactions#exit'
    get 'all_transactions/:id' => 'transactions#all_transactions'
    resources :parkings
    resources :sessions
    end

end

end

app/controllers/api/v1/transactions_controller.rb
module Api::V1
class TransactionsController < ApplicationController
  respond_to :json

def  booked_online
    transaction=Transaction.where("user_id=? AND current_transaction=?",params[:id],true).first
    if transaction.nil?
      respond_with "false"
    else
      transaction.update!(currently_in:true)
      respond_with "true"
    end
end

def exit
  transaction=Transaction.where("user_id=? AND current_transaction=?",params[:id],true).first
  if !transaction.nil?

  time_taken=(((Time.now).to_time - transaction.in)/1.hour).round
  Rails.logger.debug("Time now time: #{Time.now.inspect}")
  Rails.logger.debug("My  transaction: #{transaction.in}")
  Rails.logger.debug("My time: #{time_taken}")
  if(time_taken==0)
    time_taken=time_taken+1
  end
  out=Time.now.to_time
  parking=Parking.find_by(id: transaction.parking_id)
  parking_lot=ParkingLot.find_by(id: transaction.parking_lot_id)
  Rails.logger.debug { "#{transaction.id}" }
  cost=time_taken*parking.cost
  Rails.logger.debug("My time: #{cost.inspect}")
  transaction.update!(current_transaction:false,payment:cost,out:out)
  parking.update(filled:parking.filled-1)
  parking_lot.update(availaible:true)
  response = {status: "ok", cost: cost}
  respond_with response
  else
    response = {status: "fail"}
    respond_with response
  end
end

def all_transactions
  transactions = Transaction.where("user_id=?",params[:id]);
  response = {status: "ok", transactions: transactions}
  respond_with response
end

end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def new
  end

  def edit
  end

  def index
    #@user=current_user
    @transactions=current_user.transactions.order("created_at desc").last(5)
    #raise @transactions.inspect
    @active_transaction=current_user.transactions.find_by(current_transaction:true)
    #raise @active_transaction.inspect
  #  debugger
  end
  def payment
   customer = Stripe::Customer.retrieve(current_user.stripe_id)
      customer.sources.create(source: params[:stripeToken])
        Stripe::Charge.create(
            :customer =>  customer.id,
            :amount   =>  1000,
            :description  => "Charges By User",
            :currency => 'usd'
           )

        rescue Stripe::CardError  => e
          flash[:error] = e.message
          redirect_to root_path
  end
  def create
    @transaction = current_user.transactions.build(transaction_params)
    if @transaction.save
     flash[:success] = "transaction created!"
     redirect_to transactions_path
    else
     @feed_items = []
     flash[:error] = "Some error occured,please try again!"
     redirect_to transactions_path
   end
  end

  def update
    @transaction=Transaction.find(params[:id])
    time_taken=(((Time.now).to_time - @transaction.in)/1.hour).round
    Rails.logger.debug("Time now time: #{Time.now.inspect}")
    Rails.logger.debug("My  transaction: #{@transaction.in}")
    Rails.logger.debug("My time: #{time_taken}")
    if(time_taken==0)
      time_taken=time_taken+1
    end
    out=Time.now.to_time
    parking=Parking.find_by(id: @transaction.parking_id)
    parking_lot=ParkingLot.find_by(id: @transaction.parking_lot_id)

    cost=time_taken*parking.cost
    Rails.logger.debug("My time: #{cost.inspect}")
    @transaction.update!(current_transaction:false,payment:cost,out:out)
    parking.update(filled:parking.filled-1)
    parking_lot.update!(availaible:true)

    flash[:success] = "Transaction ended! Your total cost is Rs.#{cost}"
    redirect_to request.referrer
  end
  private


    def transaction_params
      params.require(:transaction).permit(:in,:out,:payment, :payment_type)
    end

    def correct_user
      @transaction = current_user.transaction.find_by(id: params[:id])
    #  debugger
      redirect_to(root_url) if @transaction.nil?
    end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_transaction.html.erb
<tr>
    <td><%=transaction.id%></td>
    <td><%=transaction.date%></td>
    <td><%=transaction.in.strftime("%I:%M%p")%></td>
    <td><%=transaction.out.strftime("%I:%M%p")%></td>
    <td><%=transaction.payment%></td>
    <% if transaction.payment_type %>
    <td>Cash</td>
    <%else%>
    <td>Cash</td>
    <%end%>
    <%#= raise Parking.find_by(id:transaction.parking_id).name.inspect%>
    <%# parking = Parking.find_by(id:transaction.parking_id) %>
    <%#= raise parking.name.inspect%>
    <td><%#= parking.name %></td>
  </tr>

app/views/transactions/edit.html.erb
<h1>Transactions#edit</h1>
<p>Find me in app/views/transactions/edit.html.erb</p>

app/views/transactions/index.html.erb
<% provide(:title, 'All transactions') %>
<div class="container">
<%if @active_transaction%>
<h1>Your current active transaction</h1>

<table class="table" width="100%">
  <thead>
    <tr>
    <th>T.Id</th>
    <th>Date</th>
    <th>In (time)</th>
    <th>Payment type</th>
    <th>Parking Name </th>
    <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%=@active_transaction.id%></td>
      <td><%=@active_transaction.date%></td>
      <td><%=@active_transaction.in.strftime("%I:%M%p")%></td>
      <% if @active_transaction.payment_type %>
      <td>Cash</td>
      <%else%>
      <td>Cash</td>
      <%end%>
      <%name=Parking.find_by(id:@active_transaction.parking_id).name%>
      <td><%=name%></td>
      <%if !@active_transaction.currently_in %>
      <td><%=link_to "End Transaction",end_transaction_path(@active_transaction.id), class: "btn btn-md btn-primary",:method => :get %><td>
      <%else%>
      <td>You are currently inside parking lot</td>
      <%end%>
    </tr>
  </tbody>
</table>
<%end%>
<h1>Your recent transactions</h1>
<%= link_to current_user.name, current_user %>

  <table class="table" width="100%">
    <thead>
      <tr>
      <th>T.Id</th>
      <th>Date</th>
      <th>In (time)</th>
      <th>Out(time)</th>
      <th>Payment</th>
      <th>Payment type</th>
<!--       <th>Parking Name </th> -->
      </tr>
    </thead>
    <tbody>
      <tr>
      <%= render @transactions %>
      </tr>
    </tbody>
  </table>
</div>

app/views/transactions/new.html.erb
<div class="container">
      <div class="row main">
        <div class="main-login main-center">

<br><br>
<%= form_tag payment_path do %>
  
<center>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: Rs. 10</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-email=<%= current_user.email %>
          data-locale="auto"></script>
 </center>
<% end %>
</div>
</div></div>

app/views/transactions/payment.html.erb
<div class="container">
	<center><p>Your Payment is successful!</p></center>
</div>