config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'parking_lots/update'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about'  => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get '/book_now/:id' => 'parking_lots#update' ,:as => :book_now
  get '/book_slot/:id' => 'parking_lots#update_app'
  resources :parkings
  resources :transactions
  post 'payment' => 'transactions#payment'
  get 'end_transaction/:id' =>'transactions#update', :as=> :end_transaction
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  root 'static_pages#home'

namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
    get 'book_now/:user_id/:id' => 'parking_lots#update', :as =>:book_now_api
    get 'booked_online/:id' => 'transactions#booked_online'
    get 'parking_status/:id' => 'parking_lots#parking_status'
    get 'entry/' => 'parking_lots#entry'
    get 'exit/:id' => 'transactions#exit'
    get 'all_transactions/:id' => 'transactions#all_transactions'
    resources :parkings
    resources :sessions
    end

end

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <nav>
<!--       <ul class="nav navbar-nav navbar-left">
          <li>
            <a href="https://github.com/Aditya-Chowdhry/ParkEasy" class="btn-github">
              <i class="fa fa-github fa-lg"> Follow on Github!</i>
            </a>
             </li>
      </ul> -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About",about_path %></li>
        <li><%= link_to "Help", contact_path %></li>
      </ul>
    </nav>
  </div>

</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

    <a href="<%=root_path%>" id="logo">
        <i class="fa fa-car fa-1x">EasyToPark</i>
    </a>

  <%#= link_to "ParkEasy" , root_path, id: "logo" %>

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
        <li><%= link_to "QR code", current_user.qrcode.thumb('200x200').url , :data => { :colorbox => true, :colorbox_height => '300px', :colorbox_width => '300px', :colorbox_photo => true } %>
      </li>

        <li><%= link_to "My transactions", transactions_path %></li>
        <!-- <li><%#= link_to "Users", users_path %></li> -->
           <li><%= link_to "Profile", current_user,:class =>"menu-1" %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) ,:class =>"menu-1"%></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_ie_files.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title><%= full_title(yield(:title)) %> </title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
  <%= csrf_meta_tags %>
  
  <%= render 'layouts/ie_files' %>
</head>

<div id="container">
<body>
  <%= render 'layouts/header' %>
<div id="body">

  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

<%= yield %>
</div>
  <%#= render 'layouts/footer' %>
</div>
</body>
</html>